### ISSUE TITLE
Crash still not working

### ISSUE THREAD

**Issue by gergo654** [MSourceCoded/CreativeAdditions#1]
java.lang.IllegalArgumentException: Multiple entries with same key: 
creativeadditions=FMLMod:creativeadditions{1.1.1} and creativeadditions=FMLMod:creativeadditions{1.7.10-1.1.1}
    at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
    at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
    at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
    at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
    at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166)
    at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140)
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:349)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:468)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
    at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
    at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
    at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
    at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166)
    at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140)
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:349)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:468)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 137693744 bytes (131 MB) / 265895936 bytes (253 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_A4 14 mods loaded, 0 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) 
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) 
    PlayerAPI{1.1} [Player API](minecraft.jar) 
    TooManyItems{1.7.10} [TooManyItems](minecraft.jar) 
    MapMakingTools{v2.2.2a} [Map Making Tools]([1.7.10] Map Making Tools - v2.2.2a.zip) 
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
    alluwant{2.1} [All U Want](All-U-Want 2.1.jar) 
    bettersprinting{1.0} [Better Sprinting](BetterSprinting.jar) 
    speedytoolsmod{2.0.0} [Build Faster Mod](Build-Faster-Mod-1.7.10.zip) 
    creativeadditions{1.7.10-1.1.1} [Creative Additions](creativeadditions-1.7.10-1.1.1-UNIVERSAL.jar) 
    creativeadditions{1.1.1} [Creative Additions](creativeadditions-1.7.10-1.1.1-UNIVERSAL.jar) 
    SmartCursor{1.1.6} [SmartCursor](Smart-Cursor-Mod-1.7.10.jar) 
    PrinterBlock{1.7.10} [TeeLuk's PrinterBlock](TLPrinterBlock-1.7.10.jar) 
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3621, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.
I tried everything to fix this but i cant fix it :(

**Comment by MSourceCoded** [comment]
You have 2 copies of the Creative Additions mod in your /mods/ folder, please delete one.

**Comment by Superkebabbie** [comment]
I have the same issue and I am quite sure I do not have two versions of the mod in my folder. I can see only one version (1.7.10-1.1.1, downloaded today), and when I remove it minecraft runs, but without creativeadditions (and if what you said is true and I have two versions, removing one should cause one to remain). Please advise as I am really interested in using this mod.

**Comment by gergo654** [comment]
i deleted the whole .minecraft folder and still not working

**Comment by gergo654** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10184343/5860281/ab40245c-a260-11e4-828f-d6d3aef9f0a0.png)
and now?

**Comment by gergo654** [comment]
can you make a 1.7.2 version of it? i need that functon when i can copy the command
