### ISSUE TITLE
Commands Give Unknown Error

### ISSUE THREAD

**Issue by kcmartz** [MSourceCoded/CreativeAdditions#2]
Here is the crash log. Single Player - latest forge possible (top of the list) - Minecraft 1.8.1 FML.

System 16gb ram, i7 4810mq processor, nvidia 870m graphics w/ 6gb vram (not sure if that'll help)

```
---- Minecraft Crash Report ----
// Oops.

Time: 12/20/14 6:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.<init>(Ljava/lang/String;)V
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:516)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:413)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:326)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.<init>(Ljava/lang/String;)V
    at sourcecoded.creativeA.common.Tabs$1.<init>(Tabs.java:8)
    at sourcecoded.creativeA.common.Tabs.<clinit>(Tabs.java:8)
    at sourcecoded.creativeA.item.RemoteItem.<init>(RemoteItem.java:23)
    at sourcecoded.creativeA.common.Register.<clinit>(Register.java:9)
    at sourcecoded.creativeA.CreativeAdditionsBase.preinit(CreativeAdditionsBase.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:515)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:514)
    ... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 70961536 bytes (67 MB) / 316755968 bytes (302 MB) up to 6429081600 bytes (6131 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.14.1020 3 mods loaded, 3 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{8.0.14.1020} [Forge Mod Loader] (fml-1.8-8.0.14.1020-1.8.jar) Unloaded->Constructed->Pre-initialized
    creativeadditions{1.8-2.0.0} [Creative Additions] (creativeAdditions-1.8-2.0.0-UNIVERSAL.jar) Unloaded->Constructed->Errored
```

**Comment by MSourceCoded** [comment]
According to your crash log, MinecraftForge is not installed, only Forge Mod Loader is. Please reinstall Forge 11.14.0.1273 on a fresh Minecraft 1.8 instance. 
You can find Minecraft Forge on the 1.8 branch located here: http://files.minecraftforge.net/minecraftforge//1.8

**Comment by kcmartz** [comment]
Okay so it tweens right but is super fast. How do I slow it down?

EDIT: I added '5000' to the end of the command seems to have slightly slowed it down but not slow enough.

**Comment by MSourceCoded** [comment]
The time you specify in /cam start <time> is in seconds, adding 5000 should make it almost 10 minutes long. 
Either way, I think the issue is in your MC environment, it works fine for me in both obf/deobf environments as well as for other people I've talked to. Without more information there isn't much I can do

**Comment by kcmartz** [comment]
Your plugin is the only one I have installed besides Forge itself. I allocate 6Gb of ram to Minecraft (of my 16) and run at 720p resolution with the resource pack R3dcraft.
